version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - ENCRYPTION_KEY=qIeFFgTFVVQ1ALuAeFS4
      - DATABASE_USER=teslamate
      - DATABASE_PASS=pG1tM2dP3
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=pG1tM2dP3
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=[REPLACEWITHDBPASSWORD]
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/dockerdata/teslamate-db
  teslamate-grafana-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/dockerdata/teslamate-grafana-data
  mosquitto-conf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/dockerdata/mosquitto-conf
  mosquitto-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/dockerdata/mosquitto-data
#/opt/dockerdata/
